#stage build
FROM golang:alpine as builder

RUN apk update && apk add --no-cache gcc musl-dev

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY app ./app
COPY database ./database
COPY images ./images

RUN CGO_ENABLED=1 GOOS=linux go build -a -installsuffix cgo -o main ./app

#stage execute
FROM alpine:latest

RUN apk update && apk add --no-cache libc6-compat curl

WORKDIR /root/

COPY --from=builder /app/main .
COPY --from=builder /app/database ./database
COPY --from=builder /app/images ./images

EXPOSE 9000

CMD ["./main"]